### ISSUE TITLE
New UFO STLs for Esp32?

### ISSUE THREAD

**Issue by cam-smith** [Dynatrace/ufo-esp32#15]
The Design shown in the Readme and the video for the ufo-esp32 differ from that of the original ufo.

Will you be uploading stl's for the new design?
Will we get a new parts list for which ever esp32 variant you're using?

**Comment by cinsayjames** [comment]
Any updates on getting the parts list and STL for printing?

**Comment by flyinggorilla** [comment]
Hi, the ESP32 version of the UFO has been mass-produced for purchase and thus been created with molds. Thus we dont have updated STLs.

However, the simplest workaround is to place an ESP32 Huzzah huzzah into the 3D printed UFO just inside the casing but not into the clip. Use the clip only to keep the short logo LED strips in place. That should do it without any hardware changes. Of course, feel free to design a new clip that holds an ESP32 huzzah board.

As to electronics, you will have to look into the source code of the ESP32 version to map GPIO pins properly to the Huzzah ESP32 board (or whatever ESP32 board you are choosing).

Best,
FG
