### ISSUE TITLE
Where do I find official released updates?

### ISSUE THREAD

**Issue by PatrikSteuer** [Dynatrace/ufo-esp32#17]
Where do I find the official released updates? I would require an official update so I can use our dynatrace ufo.

**Comment by flyinggorilla** [comment]
Hi Patrik, the current master branch is the latest official release. the latest binary is published in the firmware folder. this .bin file is also automatically pulled by the web-UI update feature of the ufo.

**Comment by PatrikSteuer** [comment]
Great Thanks!

**Comment by PatrikSteuer** [comment]
Great Thanks!
