### ISSUE TITLE
wiring scheme 

### ISSUE THREAD

**Issue by hamelsveld** [Dynatrace/ufo-esp32#18]
is there also a build / wiring scheme available for the esp32 module? if so where can I find it?

**Comment by helmut-s** [comment]
It's rather simple:
One button connects GPIO_NUM_0 to ground .
With this button you can switch to the ad hoc mode for configuration)
GPIO_NUM_16 is the common clock for all led stripes
GPIO_NUM_18 is data for level 1 (15leds)
GPIO_NUM_17 is data for level 2 (15leds)
GPIO_NUM_19 is data for the logo (4leds)
All led stripes needs to be supplied with ground and 5V.
The esp32 has an pin output voltage of 3.3V so the manufactured UFO does have a level shifter (to 5V) but usually the led stripes can work with 3.3V as well.

**Comment by hamelsveld** [comment]
![esp8266-nodemcu-pinout](https://user-images.githubusercontent.com/16137728/43841900-7534d680-9b24-11e8-9866-12a46b56e00c.png)
hmmm that PIN numbers I dont have :( so do you have any clue on my esp32? I've compiled the software and flashed it and that's working great. 

also I wanted to make a mini version for on my desk and using LED rings but they have only 3 wires one + one - and a data ... 

Hope you can help
