### ISSUE TITLE
Building via `make flash` from scratch does not create main/font*.h

### ISSUE THREAD

**Issue by centic9** [Dynatrace/ufo-esp32#20]
When following the build-instructions, `make flash` in a clean checkout fails with the following

```
CXX build/main/WebServer.o
/opt/dynaTrace/ufo/ufo-esp32/main/./WebServer.cpp:10:22: fatal error: fontwoff.h: No such file or directory
compilation terminated.
/opt/dynaTrace/ufo/esp-idf/make/component_wrapper.mk:273: die Regel für Ziel „WebServer.o“ scheiterte
make[1]: *** [WebServer.o] Fehler 1
/opt/dynaTrace/ufo/esp-idf/make/project.mk:450: die Regel für Ziel „component-main-build“ scheiterte
make: *** [component-main-build] Fehler 2
```

Running `make all` and then `make flash` correctly builds the missing header files.

We should either update the build-instructions in `BUILD.md` to `make all flash monitor` or fix the Makefile dependencies.

**Comment by flyinggorilla** [comment]
thanks. took your "make all flash monitor" suggestion
