### ISSUE TITLE
reload firmware

### ISSUE THREAD

**Issue by genehunter29009** [Dynatrace/ufo-esp32#26]
I need instructions to reload the firmware on an esp32 UFO. I have downloaded the firmware however there are no basic instructions. Where can I find them?

**Comment by helmut-s** [comment]
You can upload the firmware in the web ui of the UFO - in the firmware section. Or is your old firmware not working anymore?

**Comment by genehunter29009** [comment]
I tried to do the update firmware via the Web interface and it crashed. I'm trying To find out how To upload the firmware that's in the ESP 32 folderWhat adress and settingsClear skiesGene hunter
-------- Original message --------From: helmut-s <notifications@github.com> Date: 11/20/19  2:26 AM  (GMT-05:00) To: Dynatrace/ufo-esp32 <ufo-esp32@noreply.github.com> Cc: Gene Hunter <genehunter29009@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Dynatrace/ufo-esp32] reload firmware (#26) You can upload the firmware in the web ui of the UFO - in the firmware section. Or is your old firmware not working anymore?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Dynatrace/ufo-esp32/issues/26?email_source=notifications\u0026email_token=ACWQC2XR25CRTDSVJLIK5XTQUTRDLA5CNFSM4JOSF2Y2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEQ7VEA#issuecomment-555874960",
"url": "https://github.com/Dynatrace/ufo-esp32/issues/26?email_source=notifications\u0026email_token=ACWQC2XR25CRTDSVJLIK5XTQUTRDLA5CNFSM4JOSF2Y2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEEQ7VEA#issuecomment-555874960",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by helmut-s** [comment]
Very strange. You would need python and the esptool.py (on github) upload utility.
Then issue following calls (adapt the marked sections <>):
python.exe esptool.py --port <replace - e.g. com8> erase_flash
python.exe esptool.py --chip esp32 --port <replace - e.g. com8> --baud 921600 --before default_reset --after hard_reset write_flash -z --flash_mode dout --flash_freq 40m --flash_size detect 0xe000 ota_data_initial.bin 0x1000 bootloader.bin 0x10000 ufo-esp32.bin 0x8000 partitions.bin

find the needed bin files attached:
[ufo.zip](https://github.com/Dynatrace/ufo-esp32/files/3869082/ufo.zip)

You will need to install additional libraries for python (like pyserial) (the error msg will tell you).
As com port use the one that appears when you plug in the UFO to your computer

**Comment by genehunter29009** [comment]
Just wanted to update that it was successful using these settings 
0xe000 ota_data_initial.bin 
0x1000 bootloader.bin 
0x10000 ufo-esp32.bin 
0x8000 partitions.bin
I also used the flash download tool v3.6.7_1 with no issues. Much easier than having to install the esp-idf or python stuff. 
link to the flash download tool https://www.espressif.com/en/support/download/other-tools

**Comment by genehunter29009** [comment]
That did it. Thank you. I used flash tool from espiff its much easier to just use a gui.Clear skiesGene hunter
-------- Original message --------From: helmut-s <notifications@github.com> Date: 11/20/19  7:11 AM  (GMT-05:00) To: Dynatrace/ufo-esp32 <ufo-esp32@noreply.github.com> Cc: Gene Hunter <genehunter29009@gmail.com>, Author <author@noreply.github.com> Subject: Re: [Dynatrace/ufo-esp32] reload firmware (#26) Very strange. You would need python and the esptool.py (on github) upload utility.
Then issue following calls (adapt the marked sections <>):
python.exe esptool.py --port <replace - e.g. com8> erase_flash
python.exe esptool.py --chip esp32 --port <replace - e.g. com8> --baud 921600 --before default_reset --after hard_reset write_flash -z --flash_mode dout --flash_freq 40m --flash_size detect 0xe000 ota_data_initial.bin 0x1000 bootloader.bin 0x10000 ufo-esp32.bin 0x8000 partitions.bin
find the needed bin files attached:
ufo.zip

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Dynatrace/ufo-esp32/issues/26?email_source=notifications\u0026email_token=ACWQC2TDOG4DXW4F2KE67DLQUUSODA5CNFSM4JOSF2Y2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEERYWTA#issuecomment-555977548",
"url": "https://github.com/Dynatrace/ufo-esp32/issues/26?email_source=notifications\u0026email_token=ACWQC2TDOG4DXW4F2KE67DLQUUSODA5CNFSM4JOSF2Y2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEERYWTA#issuecomment-555977548",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
