### ISSUE TITLE
Dynatrace Integration

### ISSUE THREAD

**Issue by PatrikSteuer** [Dynatrace/ufo-esp32#7]
Hi, 
it seems as it is not possible to use a dynatrace installation which is not hosted by dynatrace itself. Or did I just miss the configuration? 
Regards
Patrik

**Comment by helmut-s** [comment]
That is true. Currently the URI is hardcoded to "live.dynatrace.com".
I add this to the RFE list!

**Comment by helmut-s** [comment]
There is now a new version available which does also support managed installation. You can now either enter the environment id or a (managed) URL containing the environment id in the path section (like 'https://mine.dynatrace.com/e/<environment id>')

**Comment by PatrikSteuer** [comment]
Great!

**Comment by PatrikSteuer** [comment]
Where do I find this version? It does not work, and I can still see the hardcoding in the master branch

**Comment by PatrikSteuer** [comment]
Ah, we do not use dynatrace.com as a domain. So this is the main problem right now

**Comment by PatrikSteuer** [comment]
I am not capable of writing propper cpp. Anyhow I created some coding which would solve this issue: 

```
                String delimiter = "/";
                int location = mpConfig->msDTEnvId.indexOf(delimiter);
                String host;
                String pathExtension = "";
                if (location == -1 ){
                    host = mpConfig->msDTEnvId + ".live.dynatrace.com" ;
                } else {
                    host = mpConfig->msDTEnvId.substring(0, location);
                    pathExtension = mpConfig->msDTEnvId.substring(location);
                }
                mDtUrl.Build(true, host, 443, pathExtension+"/api/v1/problem/status?Api-Token="+mpConfig->msDTApiToken);
                mDtUrlString = "https://"+host+pathExtension+"/api/v1/problem/status";
                ESP_LOGI(LOGTAG, "URL: %s", mDtUrlString.c_str());
            }
```

**Comment by helmut-s** [comment]
Since Nov 2017 it is possible to specify the complete URL as well:
specify: Environment ID (tenant) or complete URL (like 'https://mine.dynatrace.com/e/<environment id>')"
