### ISSUE TITLE
Duplicate Wifi Settings

### ISSUE THREAD

**Issue by PatrikSteuer** [Dynatrace/ufo-esp32#8]
Hi, 
why are there two possible ways to configure the wifi? 
- via make menuconfig
- via webui

I have struggles to configure a WPA2 Entreprise WIFI since the wifi config within the menuconfig does not provide this possibility.

Best
Patrik

**Comment by helmut-s** [comment]
The wifi menuconfig configuration is not used. In case there are no credentials stored in the NVS the Ufo starts in AP mode.
Please use the ui to configure wifi.

**Comment by PatrikSteuer** [comment]
It seems to work. Only problem which persists is that I am not able to connect to the ufo using it's IP address within a WPA2 Enterprise wifi. I guess that is an issue related to our network, so I close this issue
