### ISSUE TITLE
Documentation not up-to-date

### ISSUE THREAD

**Issue by Leviter** [Dynatrace/ufo-esp32#9]
I've got a pre-assembled UFO, but there is not documentation on how to use/configure it.

**Comment by Leviter** [comment]
I already figured out you need to connect to the same wifi as the UFO will start on (so: UFO). Then you will have to configure wifi. My guess that this is the wifi it has to connect to.

After applying the settings and rebooting, the LEDs are all flashing yellow. I have no clue what this means.

**Comment by helmut-s** [comment]
Sorry for that - I just updated the Wifi section. So you connected to the UFO in Ad-Hoc mode already and entered your Wifi credentials?

**Comment by helmut-s** [comment]
Flashing yellow would mean it is trying to connect. If it does not start to show the IP (in red, green or blue) then it is not able to connect

**Comment by Leviter** [comment]
Yes, I did enter the credentials, but somehow it still cannot connect. Even tried two different networks, but the yellow LEDs keep on flashing. It _does_ understand symbols in the password right? (it probably does, but I am trying to exclude anything why it should not work as expected)

**Comment by helmut-s** [comment]
What did you use? WPA2 or WPA2-Enterprise? 
There seem to be problems with the latter (currently investigating this)

**Comment by Leviter** [comment]
I tried both... One network has "WPA2 Personal" and the other one "WPA2 Enterprise". But I would prefer the latter one.

**Comment by helmut-s** [comment]
WPA2 should work - Think we should concentrate on it for now. Is the net strong at you location? Symbols should work - any special character you think which might make problems? (which I could test)

**Comment by Leviter** [comment]
I seem to get it to work on the WPA2 personal network! It does not blink yellow anymore.

**Comment by helmut-s** [comment]
There is one thing that comes to my mind which I experienced sometimes. When I configured the UFO for the very first time I had to power it off and on again in order to make the connection work. Could it be that you have done this now or was there anything else you changed?

**Comment by helmut-s** [comment]
Please let me know if you are able to make WPA2-Enterprise work as well...

**Comment by Leviter** [comment]
No, I did not power it off... but I did leave it untouched for some time. After that I changed the wifi settings again and suddenly it all started working.

I will let you know if WPA2-Enterprise starts working...  :-)

**Comment by Leviter** [comment]
The current password I am using contains an '@' sign.
